//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFrame.ImageServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageServiceReference.IImageService")]
    public interface IImageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetMyImages", ReplyAction="http://tempuri.org/IImageService/GetMyImagesResponse")]
        SmartFrame.Services.DataContracts.ImageContract GetMyImages(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetMyImages", ReplyAction="http://tempuri.org/IImageService/GetMyImagesResponse")]
        System.Threading.Tasks.Task<SmartFrame.Services.DataContracts.ImageContract> GetMyImagesAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/UploadImage", ReplyAction="http://tempuri.org/IImageService/UploadImageResponse")]
        bool UploadImage(byte[] imageBytes, int moodId, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/UploadImage", ReplyAction="http://tempuri.org/IImageService/UploadImageResponse")]
        System.Threading.Tasks.Task<bool> UploadImageAsync(byte[] imageBytes, int moodId, string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImageServiceChannel : SmartFrame.ImageServiceReference.IImageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageServiceClient : System.ServiceModel.ClientBase<SmartFrame.ImageServiceReference.IImageService>, SmartFrame.ImageServiceReference.IImageService {
        
        public ImageServiceClient() {
        }
        
        public ImageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SmartFrame.Services.DataContracts.ImageContract GetMyImages(string username) {
            return base.Channel.GetMyImages(username);
        }
        
        public System.Threading.Tasks.Task<SmartFrame.Services.DataContracts.ImageContract> GetMyImagesAsync(string username) {
            return base.Channel.GetMyImagesAsync(username);
        }
        
        public bool UploadImage(byte[] imageBytes, int moodId, string userName) {
            return base.Channel.UploadImage(imageBytes, moodId, userName);
        }
        
        public System.Threading.Tasks.Task<bool> UploadImageAsync(byte[] imageBytes, int moodId, string userName) {
            return base.Channel.UploadImageAsync(imageBytes, moodId, userName);
        }
    }
}
